# CMake generated Testfile for 
# Source directory: /home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test
# Build directory: /home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testdbusmessage "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/dbus_wrapper.sh" "/usr/bin/dbus-daemon" "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testdbusmessage")
set_tests_properties(testdbusmessage PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;53;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testdbus "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/dbus_wrapper.sh" "/usr/bin/dbus-daemon" "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testdbus")
set_tests_properties(testdbus PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;53;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testservicewatcher "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/dbus_wrapper.sh" "/usr/bin/dbus-daemon" "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testservicewatcher")
set_tests_properties(testservicewatcher PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;53;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testflags "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testflags")
set_tests_properties(testflags PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(teststringutils "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/teststringutils")
set_tests_properties(teststringutils PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testkey "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testkey")
set_tests_properties(testkey PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testutf8 "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testutf8")
set_tests_properties(testutf8 PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testcolor "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testcolor")
set_tests_properties(testcolor PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testi18nstring "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testi18nstring")
set_tests_properties(testi18nstring PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testevent "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testevent")
set_tests_properties(testevent PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testlist "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testlist")
set_tests_properties(testlist PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testfs "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testfs")
set_tests_properties(testfs PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testlibrary "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testlibrary")
set_tests_properties(testlibrary PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(teststandardpath "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/teststandardpath")
set_tests_properties(teststandardpath PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testunixfd "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testunixfd")
set_tests_properties(testunixfd PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testmetastring "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testmetastring")
set_tests_properties(testmetastring PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testhandlertable "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testhandlertable")
set_tests_properties(testhandlertable PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testsignals "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testsignals")
set_tests_properties(testsignals PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testinputbuffer "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testinputbuffer")
set_tests_properties(testinputbuffer PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testlog "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testlog")
set_tests_properties(testlog PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testeventdispatcher "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testeventdispatcher")
set_tests_properties(testeventdispatcher PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testrect "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testrect")
set_tests_properties(testrect PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testfallbackuuid "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testfallbackuuid")
set_tests_properties(testfallbackuuid PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testsemver "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testsemver")
set_tests_properties(testsemver PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;62;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testconfig "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testconfig")
set_tests_properties(testconfig PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;77;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testconfigdbus "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testconfigdbus")
set_tests_properties(testconfigdbus PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;77;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testinputcontext "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testinputcontext")
set_tests_properties(testinputcontext PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testsurroundingtext "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testsurroundingtext")
set_tests_properties(testsurroundingtext PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testaddon "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testaddon")
set_tests_properties(testaddon PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testmenu "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testmenu")
set_tests_properties(testmenu PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testuserinterfacemanager "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testuserinterfacemanager")
set_tests_properties(testuserinterfacemanager PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testelement "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testelement")
set_tests_properties(testelement PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testcandidatelist "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testcandidatelist")
set_tests_properties(testcandidatelist PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testicontheme "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testicontheme")
set_tests_properties(testicontheme PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testtext "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testtext")
set_tests_properties(testtext PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testinstance "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testinstance")
set_tests_properties(testinstance PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;98;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testxkbrules "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testxkbrules")
set_tests_properties(testxkbrules PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;109;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testisocodes "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testisocodes")
set_tests_properties(testisocodes PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;115;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testcompose "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testcompose")
set_tests_properties(testcompose PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;119;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testemoji "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testemoji")
set_tests_properties(testemoji PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;126;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testunicode "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testunicode")
set_tests_properties(testunicode PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;132;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testspell "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testspell")
set_tests_properties(testspell PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;139;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
add_test(testquickphrase "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/testquickphrase")
set_tests_properties(testquickphrase PROPERTIES  _BACKTRACE_TRIPLES "/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;145;add_test;/home/czg_arch/fcitx5_build/src/fcitx5-5.1.8/test/CMakeLists.txt;0;")
subdirs("addon")
